model_name: 'GCN'
project: 'collab-GCN-PE'
group: 'GCN-clique4-PE'
name: 'GCN-clique4-PE'
use_counts: True
count_files: ['collab_clique4_counts.json']
idx_list: []
pe_dim: 8
description: '4 clique, positional encoding'
