model_name: 'SAGE'
project: 'collab-SAGE-PE'
group: 'SAGE-path5-multsum-PE'
name: 'SAGE-path5-multsum-PE'
use_counts: True
count_files: ['collab_path5_counts.json']
idx_list: []
pe_dim: 6
description: '5 path, positional encoding, with multsum'